### ISSUE TITLE
Missing verification check in callbacks

### ISSUE THREAD

**Issue by Alexangelj** [verumlotus/PrimitiveThetaVaults#3]
https://github.com/verumlotus/PrimitiveThetaVaults/blob/7491956ae24f61de231c60bbc511a7557b08ab63/src/vaults/VaultPrimitiveInteractions.sol#L222-L229

## Attacker scenario:
- Attacker calls `allocate()`
- `allocate` triggers `allocateCallback` in Attacker's contract
- Attacker's contract's `allocateCallback` calls PrimitiveThetaVault `allocateCallback`
- Theta vault transfers tokens to Engine
- Exit callback
- Engine checks to see if tokens were paid
- Succeeds

## Fix
Add a static check to compute engine address and compare it against `msg.sender`

reference: https://github.com/primitivefinance/rmm-manager/blob/2cf4750e978a22d44386e063b85a858d56e22ccb/contracts/PrimitiveManager.sol#L143-L144

**Comment by verumlotus** [comment]
Good catch sir – also anyone could've invoked these callback funcs and randomly sent the vault's tokens to the engine lol 🤪
